version: "3"
services:
 reverseproxy:
    build:
        context: .
    image: webedhmb/reverseproxy 
 backend_user:
    build:
        context: ../../udacity-c3-restapi-user
    image: webedhmb/udacity-restapi-user
 backend_feed:
    build:
        context: ../../udacity-c3-restapi-feed 
    image: webedhmb/udacity-restapi-feed
 frontend:
    build:
        context: ../../udacity-c3-frontend 
    image: webedhmb/udacity-frontend